apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: idbi-apim-es-cluster
  annotations:
    # Having this annotation so that headless service always registers the IP address irrespective of probe status.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  namespace: nsp-idbi-apim-prod
spec:
  serviceName: idbi-apim-es-svc-h
  replicas: 3
  selector:
    matchLabels:
      app: idbi-apim-es-cluster
  template:
    metadata:
      labels:
        app: idbi-apim-es-cluster
    spec:
      terminationGracePeriodSeconds: 10
      # affinity:
      #   # Pods will be placed in the worker node that has the label es-node=internaldatastore
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: es-node
      #           operator: In
      #           values:
      #             - internaldatastore
      #   # Pods will label app=idbi-apim-es-cluster will not be placed together
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #           - key: app
      #             operator: In
      #             values:
      #               - idbi-apim-es-cluster
      #         topologyKey: kubernetes.io/hostname

      # # Toleration condition for Pods when the node is tainted and the subsequent effect
      # tolerations:
      # - key: "es-tainted-node"
      #   operator: "Equal"
      #   value: "internaldatastore"
      #   effect: "NoSchedule"
      imagePullSecrets:
      - name: dockerrepocred
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: esdata
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: idbi-apim-es-server
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1
        resources:
          limits:
            cpu: "1"
            memory: "2Gi" 
          requests:
            cpu: "0.25"
            memory: "1Gi"
        ports:
        - containerPort: 9200
          name: rest-api
          protocol: TCP
        - containerPort: 9300
          name: inter-node-comm
          protocol: TCP
        volumeMounts:
        - name: esdata
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: "CLUSTER_NAME"
            value: SAG_EventDataStore
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: "NUMBER_OF_MASTERS"
            value: "2"
          - name: NODE_MASTER
            value: "true"
          - name: NODE_INGEST
            value: "true"
          - name: NODE_DATA
            value: "true"
          - name: HTTP_ENABLE
            value: "false"
          - name: discovery.seed_hosts
            value: "idbi-apim-es-cluster-0.idbi-apim-es-svc-h.nsp-idbi-apim-prod.svc.cluster.local:9300,idbi-apim-es-cluster-1.idbi-apim-es-svc-h.nsp-idbi-apim-prod.svc.cluster.local:9300, idbi-apim-es-cluster-2.idbi-apim-es-svc-h.nsp-idbi-apim-prod.svc.cluster.local:9300"
          - name: cluster.initial_master_nodes
            value: "idbi-apim-es-cluster-0,idbi-apim-es-cluster-1,idbi-apim-es-cluster-2"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
     
  volumeClaimTemplates:
  - metadata:
      name: esdata
      labels:
        type: hostPath
    spec:
      storageClassName: standard
      accessModes: 
      - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
           

