---
apiVersion: v1
kind: Service
metadata:
  name: idbi-es-svc-nodeport
  labels:
    app: idbi-es-svc-nodeport
  namespace: nsp-idbi-apim-prod
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: idbi-apim-es-cluster
  ports:
    - name: is-port
      port: 9200
      targetPort: 9200
      nodePort: 30016
    - name: comm-port
      port: 9300
      targetPort: 9300
      nodePort: 30017