apiVersion: apps/v1
kind: Deployment
metadata:
  name:  idbi-apim-kibana
  namespace: nsp-idbi-apim-prod
  labels:
    component: kibana
spec:
  replicas: 2
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      # affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - key: elasticsearch-node
      #         operator: In
      #         values:
      #         - elasticsearch
      # # Pods will label component=kibana will not be placed together
      #   podAntiAffinity:
      #      requiredDuringSchedulingIgnoredDuringExecution:
      #        - labelSelector:
      #            matchExpressions:
      #            - key: component
      #              operator: In
      #              values:
      #                - kibana
      #          topologyKey: "kubernetes.io/hostname"
      # tolerations:
      # - key: "node-role.kubernetes.io/elasticsearch"
      #   operator: "Exists"
      #   effect: "NoSchedule"

      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:7.7.1
        env:
        - name: "CLUSTER_NAME"
          value: "SAG_EventDataStore"
        - name: "ELASTICSEARCH_URL"
          value: 'http://idbi-apim-es-svc-h.nsp-idbi-apim-prod.svc.cluster.local:9200'
        resources:
          requests:
            cpu: "0.25"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1.5Gi"
        ports:
        - containerPort: 5601
          #name: kibana
          protocol: TCP
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /api/status
            port: 5601
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /api/status
            port: 5601
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: kibana-config
          mountPath: /tmp/kibana.yml
          subPath: kibana.yml
          readOnly: false
        command:
        - /bin/bash
        - -c
        - |
         cp /tmp/kibana.yml /usr/share/kibana/config/kibana.yml
         /usr/share/kibana/bin/kibana
      volumes:
      - name: kibana-config
        configMap:
          name: idbi-apim-kibana-config
          items:
          - key: kibana.yml
            path: kibana.yml
          defaultMode: 0777

