apiVersion: v1
kind: Service
metadata:
  name: idbi-apim-kibana-svc-nodeport
  namespace: nsp-idbi-apim-prod
  labels:
    component: kibana
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    component: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    nodePort: 30045
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: idbi-apim-kibana-svc
  namespace: nsp-idbi-apim-prod
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    protocol: TCP
